# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sdk_com.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'sdk_com.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsdk_com.proto\x12\x05\x62vsdk\x1a\x19google/protobuf/any.proto\"\xda\x01\n\rMqttMsgHeader\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x13\n\x0bmac_address\x18\x02 \x01(\t\x12\x12\n\nlogin_name\x18\x03 \x01(\t\x12\x0e\n\x06\x63md_id\x18\x04 \x03(\x05\x12.\n\x08\x63md_type\x18\x05 \x01(\x0e\x32\x1c.bvsdk.MqttMsgHeader.CmdType\"O\n\x07\x43mdType\x12\x0f\n\x0bkAppRequest\x10\x00\x12\x0b\n\x07kAppCmd\x10\x01\x12\x11\n\rkDeviceReport\x10\x02\x12\x13\n\x0fkServiceRequest\x10\x03\"S\n\x07MqttMsg\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.bvsdk.MqttMsgHeader\x12\"\n\x04\x62ody\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\"J\n\x0bMqttMsgBody\x12\x11\n\tint_value\x18\x01 \x01(\x05\x12\x12\n\nbool_value\x18\x02 \x01(\x08\x12\x14\n\x0cstring_value\x18\x03 \x01(\t\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\".\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05\x61ngle\x18\x03 \x01(\x05\"6\n\x04Line\x12\n\n\x02x0\x18\x01 \x01(\x05\x12\n\n\x02y0\x18\x02 \x01(\x05\x12\n\n\x02x1\x18\x03 \x01(\x05\x12\n\n\x02y1\x18\x04 \x01(\x05\"7\n\x07Polygon\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x1c\n\x06points\x18\x02 \x03(\x0b\x32\x0c.bvsdk.Point\"q\n\x08WifiInfo\x12\x13\n\x0bmac_address\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x0c\n\x04ssid\x18\x03 \x01(\t\x12\x0f\n\x07\x65ncrypt\x18\x04 \x01(\x08\x12\x0b\n\x03psk\x18\x05 \x01(\t\x12\x10\n\x08strength\x18\x06 \x01(\x05*\x1e\n\x0bOnlineCmdId\x12\x0f\n\x0bkOnlineInfo\x10\x00*-\n\x08OtaCmdId\x12\x0f\n\x0bkOtaMessage\x10\x00\x12\x10\n\x0ckOtaProgress\x10\x01*/\n\x0bServerCmdId\x12\x11\n\rkGetDeviceLog\x10\x00\x12\r\n\tkShellCmd\x10\x01*4\n\nStateCmdId\x12\x10\n\x0ckDeviceState\x10\x00\x12\x14\n\x10kDevBatteryLevel\x10\x01*2\n\x0eLoginNameCmdId\x12\x0f\n\x0bkHomeStatus\x10\x00\x12\x0f\n\x0bkDeviceInfo\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdk_com_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ONLINECMDID']._serialized_start=740
  _globals['_ONLINECMDID']._serialized_end=770
  _globals['_OTACMDID']._serialized_start=772
  _globals['_OTACMDID']._serialized_end=817
  _globals['_SERVERCMDID']._serialized_start=819
  _globals['_SERVERCMDID']._serialized_end=866
  _globals['_STATECMDID']._serialized_start=868
  _globals['_STATECMDID']._serialized_end=920
  _globals['_LOGINNAMECMDID']._serialized_start=922
  _globals['_LOGINNAMECMDID']._serialized_end=972
  _globals['_MQTTMSGHEADER']._serialized_start=52
  _globals['_MQTTMSGHEADER']._serialized_end=270
  _globals['_MQTTMSGHEADER_CMDTYPE']._serialized_start=191
  _globals['_MQTTMSGHEADER_CMDTYPE']._serialized_end=270
  _globals['_MQTTMSG']._serialized_start=272
  _globals['_MQTTMSG']._serialized_end=355
  _globals['_MQTTMSGBODY']._serialized_start=357
  _globals['_MQTTMSGBODY']._serialized_end=431
  _globals['_POINT']._serialized_start=433
  _globals['_POINT']._serialized_end=462
  _globals['_POINT3D']._serialized_start=464
  _globals['_POINT3D']._serialized_end=510
  _globals['_LINE']._serialized_start=512
  _globals['_LINE']._serialized_end=566
  _globals['_POLYGON']._serialized_start=568
  _globals['_POLYGON']._serialized_end=623
  _globals['_WIFIINFO']._serialized_start=625
  _globals['_WIFIINFO']._serialized_end=738
# @@protoc_insertion_point(module_scope)
